---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Unarchive a file that needs to be downloaded
    unarchive:
      src: https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

